### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [marv42/EbtNewNote#12]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 118 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on EbtNewNote (or its library dependencies). We documented these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve EbtNewNote's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by marv42** [comment]
Yes, please share those gists with me.

-- 
Marvin

**Comment by misterAnderson90** [comment]
Hello Marvin,

I have tried to build the debug version of the app to fix the code obfuscation problem but I didn't succeed. From the 118 warnings that CogniCrypt reported, we randomly selected 5 gists to share with you. If you are interested, we can share the report with all warnings. We can also rerun the analysis without code obfuscation if you send the debug version of the app. 

[Gist 01 - SSLContext](https://gist.github.com/misterAnderson90/40db7c6861ba28a34fc6e604808bbba8)
[Gist 02 - TrustManagerFactory](https://gist.github.com/misterAnderson90/5fdc7ca73e34e396af781894d4727cd8)
[Gist 03 - SSLContext](https://gist.github.com/misterAnderson90/6c12462de5c359d4d2464de55d713b6c)
[Gist 04 - KeyFactory](https://gist.github.com/misterAnderson90/3aa73cce5ad9fd17d824aff899aa9be6)
[Gist 05 - Signature](https://gist.github.com/misterAnderson90/187c56962d96bfafb206829e0a1f7a68)

For any doubts, you can comment directly in the gists and we can clarify the issues.  

Best regards,

**Comment by misterAnderson90** [comment]
Hello @marv42,

Did you have time to evaluate these issues? How do you perceive the warnings reported by this SAST tool?

**Comment by marv42** [comment]
The warnings do not concern the app code itself but code of included libraries.
