### ISSUE TITLE
No camera button in portrait mode

### ISSUE THREAD

**Issue by scy** [marv42/EbtNewNote#2]
Hi there! I’m using EBT New Note 0.19 (installed via F-Droid, there’s no more recent version available).

In portrait mode, I don’t see the OCR camera button. However, it does appear once I flip the phone into landscape mode.

I’ll attach screenshots in a minute.

**Comment by scy** [comment]
![Screenshot_20200228-130210](https://user-images.githubusercontent.com/28629/75548173-ed07e580-5a2c-11ea-9db1-744bdfd6d8d6.png)

![Screenshot_20200228-130419](https://user-images.githubusercontent.com/28629/75548189-f98c3e00-5a2c-11ea-9c4b-fc8658632bf1.png)

**Comment by marv42** [comment]
Hi!
Thanks for the feedback.
I will have a look into this as soon as i will have a reasonable internet connection again. ;-) (I am moving into a new apartment atm.)

**Comment by marv42** [comment]
Fix released in v 0.43.0
