### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [marv42/EbtNewNote#21]
fail log: [com.marv42.ebt.newnote_7200.log.gz.ZIP](https://github.com/marv42/EbtNewNote/files/13347704/com.marv42.ebt.newnote_7200.log.gz.ZIP) _(remove .ZIP)_

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/88aa5bca5311d8284e714c61536c9d9666db3bbc

**Comment by licaon-kter** [comment]
Umm?

**Comment by marv42** [comment]
Pipeline passed, right?
https://gitlab.com/fdroid/fdroiddata/-/pipelines/1071779795
Something else to do?

**Comment by licaon-kter** [comment]
Can you read the commit title though? :)

**Comment by licaon-kter** [comment]
> Something else to do?

Yes, fix the issue as mentioned in the attached log.

**Comment by marv42** [comment]
Didn't you fix it with this PR?
https://github.com/marv42/EbtNewNote/pull/20/commits/753000d8ce3dae464c4746d4cfb1a8c505bc1eb1

**Comment by licaon-kter** [comment]
No, that's a fix for another issue.
