### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [marv42/EbtNewNote#24]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6514220371

```
 Build file '/home/vagrant/build/com.marv42.ebt.newnote/app/build.gradle' line: 21
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not set unknown property 'prettyPrint' for extension 'aboutLibraries' of type com.mikepenz.aboutlibraries.plugin.AboutLibrariesExtension.
```

Could you please take a look? Thanks!

**Comment by marv42** [comment]
I tried several things but could not resolve the issue.
It runs perfectly normal on my machine™️.
Any hints would be greatly appreciated.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6515037160 It still fails.
