### ISSUE TITLE
OCR API key not saved

### ISSUE THREAD

**Issue by scy** [marv42/EbtNewNote#3]
Hi there! I’m using EBT New Note 0.19 from F-Droid (there’s no more recent version available).

It appears that the OCR API key is not saved correctly. When restarting the app, switching between screen orientations or switching between apps, sometimes (but not always) the dialog asking for the API key reappears.

Is there a way I can help you debug this further? Or is it maybe fixed in a more recent version? Apparently, there have been multiple releases in the mean time, but they are not available on F-Droid.

**Comment by marv42** [comment]
The newer versions of the app have not tackled the above issue.
I will try to reproduce the error on virtual devices.
If i don't succeed, i will come back to you.

**Comment by marv42** [comment]
Fix released in v 0.43.0
