### ISSUE TITLE
Suggestion: Local OCR

### ISSUE THREAD

**Issue by scy** [marv42/EbtNewNote#4]
I get why you’re using an online OCR service: It’s probably way easier to implement.

However, during the time it takes to take a photo, confirm it, upload it to the service and having it recognized, I can probably input the serial number by hand twice. (Of course that’s dependent on one’s connection speed.)

I wonder whether you’ve tried using an OCR library that could do the recognition directly on the phone. Not that I know of any, but I’m no Android developer anyway. But since Euro bill serial numbers use an OCR-optimized font and there’s usually no other text around it, even a pretty simple library could maybe do it easily.

**Comment by marv42** [comment]
I chose the online OCR service because i wanted to reduce the usage of external libraries.
I might have a look into OCR libraries when i have the time, but you would still need to take the photo and confirm it. ;-)

**Comment by marv42** [comment]
e.g. https://github.com/adaptech-cz/Tesseract4Android

**Comment by marv42** [comment]
Implemented for testing

**Comment by marv42** [comment]
Published in v 0.71.0
